blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/jaaparjazzery/aws-terraform-modules/discussions
    about: Ask questions and discuss with the community
  - name: Documentation
    url: https://github.com/jaaparjazzery/aws-terraform-modules/blob/main/README.md
    about: Read the documentation
  - name: Security Issue
    url: https://github.com/jaaparjazzery/aws-terraform-modules/security/advisories/new
    about: Report a security vulnerability (private)
